# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        # Use the same Python version used the Dockerfile
        python-version: [3.12]

    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}

    steps:
      # Checkout and env setup
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1.2.3
        with:
          exclude: "examples/example[3-4].wav"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/runtime.txt
          pip install -r requirements/optional.txt
          pip install -e .

      - name: Check with pre-commit
        run: |
          SKIP=hadolint pre-commit
          SKIP=hadolint pre-commit run --all-files

      - name: Run tests and coverage
        run: |
          set -ex
          pytest --cov=batbot --cov-append --cov-report=xml --random-order-seed=1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.BATBOT_CODECOV_TOKEN }}
          files: ./coverage/coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
